apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: school-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
  - host: school-app.com
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: school-backend
            port:
              number: 80
