apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://127.0.0.1:49628
  name: colima
contexts:
- context:
    cluster: colima
    user: colima
  name: colima
current-context: colima
kind: Config
preferences: {}
users:
- name: colima
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJrVENDQVRlZ0F3SUJBZ0lJRlNNdEgzZGtlZmN3Q2dZSUtvWkl6ajBFQXdJd0l6RWhNQjhHQTFVRUF3d1kKYXpOekxXTnNhV1Z1ZEMxallVQXhOelk1TkRreU5UWXpNQjRYRFRJMk1ERXlOekExTkRJME0xb1hEVEkzTURFeQpOekExTkRJME0xb3dNREVYTUJVR0ExVUVDaE1PYzNsemRHVnRPbTFoYzNSbGNuTXhGVEFUQmdOVkJBTVRESE41CmMzUmxiVHBoWkcxcGJqQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJKV3BocjNuMDdmaTE1ZkIKam1JSEFtMTdoLzhZMGJnSEpYcFJyamlYZ2lZczltOENsTURvTWxGc082UEFnMnVyL0pPVGl0Um1uSUROelZhdAo0dHRUSm1xalNEQkdNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY0RBakFmCkJnTlZIU01FR0RBV2dCUVNVdWNSbWxXSy82bkhaOUpxMUp4cmVyTXVzekFLQmdncWhrak9QUVFEQWdOSUFEQkYKQWlFQThESVBnNkxsK0wrNG9RaldDOW5PU2dBdStPZEQrOFNsTkh5eWl1UmNKRUVDSUFPZ0lzN29GdTFXaUlobwppM3NJQWJzeHZMSXQxQVkxN3pRaFdBczUvK216Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdFkyeHAKWlc1MExXTmhRREUzTmprME9USTFOak13SGhjTk1qWXdNVEkzTURVME1qUXpXaGNOTXpZd01USTFNRFUwTWpRegpXakFqTVNFd0h3WURWUVFEREJock0zTXRZMnhwWlc1MExXTmhRREUzTmprME9USTFOak13V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFTb1VIeTVPanMrWi9KUUJhNEpEbFI3eWxhYlpVVS80akQvc0cwcW5vRzcKTko0RHR3M0cyaGR2VmtuazQwdFl1eTJJdjAzUm5wamIxK0tRbHdCSXhXbTFvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVUVsTG5FWnBWaXYrcHgyZlNhdFNjCmEzcXpMck13Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUlnSlBUZ3ExaExvRkVnMXZYR2dTY2ZtQUtqWHE1dmt5cEEKL2svN0N1NWpvNzhDSVFDWDA1SGV1NnB3UkM3dXN4TTVCUzZIbWp0MGRlblJlN3E3T3ltMTh0RVEvdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    client-key-data: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSU9BOHB6WDlOTjdneXVTZ0RpenhRQllydy82Vzhvc3ArTkhNTEZnb0NvYytvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFbGFtR3ZlZlR0K0xYbDhHT1lnY0NiWHVIL3hqUnVBY2xlbEd1T0plQ0ppejJid0tVd09neQpVV3c3bzhDRGE2djhrNU9LMUdhY2dNM05WcTNpMjFNbWFnPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
