apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: school-management-dev

generatorOptions:
  disableNameSuffixHash: true

resources:
- ../../../base/vault

patches:
- path: vault-patch.yaml

secretGenerator:
- name: vault-secret
  literals:
  - root-token=root
  type: Opaque
