site_name: School Management Documentation
site_url: http://localhost:8000/

theme:
  name: material
  language: en
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
